### ISSUE TITLE
POW-HVM4.5K-24V/POW-HVM6.5K-48V support

### ISSUE THREAD

**Issue by lordlightman** [odya/esphome-powmr-hybrid-inverter#47]
Hello there.

Does anyone know if newer PowMr inverters like POW-HVM4.5K-24V/POW-HVM6.5K-48V are supported?

**Comment by lufton** [comment]
@lordlightman no, but you can check my repository for your inverter, it should work: https://github.com/lufton/esphome-inv-8851

**Comment by lordlightman** [comment]
Hello @lufton, thanks, I will check your repo.

**Comment by PZotya** [comment]
Leodesigner made a project for the communication basics, which uses the inv8851 also. In this documentation he emphasizes, that the setting modification is available only after requesting a config, and sending it back the modified one. Does it can work with this project?
Leodesigner's project for the POW-HVM4.5K-24V/POW-HVM6.5K-48V inverter communication: https://github.com/leodesigner/powmr4500_comm/tree/main

**Comment by lufton** [comment]
@PZotya, my project works perfectly with setting  parameters. The way it works it periodically requests state, then replaces parameter bit and pushing this config back.

**Comment by PZotya** [comment]
> @PZotya, my project works perfectly with setting parameters. The way it works it periodically requests state, then replaces parameter bit and pushing this config back.

Hi Lufton!

Thanks for this good work!
I was able to use Your ESPHome setup for my PowMr inverter and HomeAssistant. But I have a problem, that all my entities of this device is Unknown. What is that I made wrong?

**Comment by lufton** [comment]
@PZotya please open corresponding issue in my project. Specify witch hardware you use and your setup details including software version of inverter.
